name: deploy-container

on:
  push:
    branches: [main]
    paths:
      - 'container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - name: Setup - GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Deploy
        run: gsutil -m rsync -R output gs://${{ GCS_BUCKET }}
#      - uses: chrislennon/action-aws-cli@v1.1
#      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
